name: 'app-randomdog'

on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:
  
jobs:
  DOSOMETHING:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run app-randomdog
        run: |
          python ./randomdog/randomdog.py ${{ secrets.SECRET }}
          echo Done! File should be pushed!
